web-twofactor/src/app/routes.py
from flask import render_template, send_from_directory, Blueprint, redirect, url_for, request, abort, flash
from . import static_folder, login_manager, db
from flask_login import login_required, logout_user, current_user, login_user
from .forms import CreateUserForm, LoginUserForm, MFAUserForm
from .models import User
import pyotp


main = Blueprint("main", __name__)


@main.route('/robots.txt')
@main.route('/security.txt')
def static_from_root():
    return send_from_directory(static_folder, request.path[1:])


@main.route('/favicon.ico')
def favicon():
    return send_from_directory(static_folder, 'img/')


@main.route('/')
@login_required
def index():
    return render_template('home.html', current_user=current_user)


@main.route('/auth/', methods=['GET', 'POST'])
def auth():
    login_form = LoginUserForm(prefix="login")
    create_form = CreateUserForm(prefix="create")

    active_pane = 'login' if request.form.get('form_name') is None else request.form.get('form_name')

    if current_user.is_authenticated:
        flash('You are already logged in!', 'warning')
        return redirect(url_for('main.index'))

    if request.method == 'POST':
        if request.form.get('form_name') == 'create' and create_form.validate_on_submit():
            active_pane = 'create'
            user = User.query.filter_by(email=create_form.email.data).first()

            if user is None:
                new_user = User(
                    name=create_form.name.data,
                    email=create_form.email.data,
                    password=create_form.password.data
                )

                db.session.add(new_user)
                db.session.flush()
                db.session.commit()

                flash('Account has been created however it must be activated by an administrator', 'success')
            else:
                flash('Email address cannot be used', 'warning')

            return redirect(url_for('main.auth'))

        if request.form.get('form_name') == 'login' and login_form.validate_on_submit():
            user = User.query.filter_by(email=login_form.email.data).first()

            if user is None:
                flash('Could not log you in, please try again.', 'danger')
            elif not user.verify_password(login_form.password.data):
                flash('Could not log you in please try again.', 'danger')
            else:
                login_user(user, remember=True)

                return redirect(url_for('main.auth_mfa', next=request.args.get('next')))

    return render_template('auth.html', login_user=login_form, create_user=create_form, active_pane=active_pane)


@main.route('/auth/mfa', methods=['GET', 'POST'])
@login_required
def auth_mfa():
    mfa_form = MFAUserForm(prefix="mfa")
    active_pane = 'mfa'

    if request.method == 'POST':
        user = User.query.filter_by(email=current_user.email)

        if not user:
            flash('Oh no', 'error')
        else:
            if user.otp_secret is None:
                flash('User does not have MFA setup. Please do this otherwise your account is insecure', 'warning')
                return redirect(url_for('main.index', next=request.args.get('next')))
            totp = pyotp.TOTP(user.otp_secret)
            if totp.verify(mfa_form.code.data):
                login_user(user)
                return redirect(url_for('main.index', next=request.args.get('next')))
            else:
                flash('Invalid OTP token.', 'warning')
                return redirect(url_for('main.index', next=request.args.get('next')))

    return render_template('auth_mfa.html', mfa_user=mfa_form, active_pane=active_pane)


@main.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for("main.auth"))


@login_manager.user_loader
def load_user(user_id):
    """Check if user is logged-in on every page load."""
    if user_id is not None:
        return User.query.get(user_id)

    return None


@login_manager.unauthorized_handler
def unauthorized_callback():
    return redirect(url_for("main.auth", next=request.path))

web-twofactor/src/app/templates/auth.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block description %}Please login{% endblock %}

{% block content %}
<div class="container-fluid text-light py-5 px-3">
	<div class="container">
		<h1 class="display-4">Access is restricted.</h1>
		{% include "components/alert.html" %}

		<ul class="nav nav-pills nav-pills-light mb-3" id="tabs_list" role="tablist">
			<li class="nav-item" role="presentation">
				<a class="nav-link{% if active_pane == 'login' %} active{% endif %} text-light" id="login_tab" data-bs-toggle="pill" data-bs-target="#login_pane" href="#login_pane" role="tab" aria-controls="login_pane" aria-selected="true">Login</a>
			</li>
			<li class="nav-item" role="presentation">
				<a class="nav-link{% if active_pane == 'create' %} active{% endif %} text-light" id="create_tab" data-bs-toggle="pill" data-bs-target="#create_pane" href="#create_pane"  role="tab" aria-controls="create_pane" aria-selected="false">Create</a>
			</li>
			<li class="nav-item" role="presentation">
				<a class="nav-link text-light" id="forgot_tab" data-bs-toggle="pill" data-bs-target="#forgot_pane" href="#forgot_pane"  role="tab" aria-controls="forgot_pane" aria-selected="false">Forgot</a>
			</li>
		</ul>

		<div class="tab-content" id="content">
			<div class="tab-pane fade{% if active_pane == 'login' %} show active{% endif %}" id="login_pane" role="tabpanel" aria-labelledby="login_tab">
				{% for field, errors in login_user.errors.items() %}
					<div class="alert alert-info alert-danger alert-dismissible fade show" role="alert">
						{{ login_user[field].label }}: {{ ', '.join(errors) }}
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					</div>
				{% endfor %}
				<form id="login_form" action="{{ url_for('main.auth') }}" name="login_form" method="POST">
					<input type="hidden" class="d-none" name="form_name" value="login" />
					{{ login_user.csrf_token }}
					<div class="mb-3 ">
						{{ login_user.email.label(class="form-label") }}
						{{ login_user.email(class="form-control") }}
						<small id="emailHelp" class="form-text text-light">Please enter your registered email.</small>
					</div>
					<div class="mb-3 ">
						{{ login_user.password.label(class="form-label") }}
						{{ login_user.password(class="form-control") }}
					</div>
					{{ login_user.submit(class='btn btn-primary') }}
				</form>
			</div>
			<div class="tab-pane fade{% if active_pane == 'create' %} show active{% endif %}" id="create_pane" role="tabpanel" aria-labelledby="create_tab">
				{% for field, errors in create_user.errors.items() %}
					<div class="alert alert-info alert-danger alert-dismissible fade show" role="alert">
						{{ create_user[field].label }} error: {{ ', '.join(errors) }}
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					</div>
				{% endfor %}
				<form id="create_form" action="{{ url_for('main.auth') }}" name="create_form" method="POST">
					<input type="hidden" class="d-none" name="form_name" value="create" />
					{{ create_user.csrf_token }}
					<div class="mb-3 ">
						{{ create_user.name.label(class="form-label") }}
						{{ create_user.name(class="form-control") }}
						<small id="name_help" class="form-text text-light">X Æ A-12 will not pass my validation checks so don't try.</small>
					</div>
					<div class="mb-3 ">
						{{ create_user.email.label(class="form-label") }}
						{{ create_user.email(class="form-control") }}
					</div>
					<div class="mb-3 ">
						{{ create_user.password.label(class="form-label") }}
						{{ create_user.password(class="form-control") }}
					</div>
					{{ create_user.submit(class='btn btn-secondary text-light') }}
					<br />
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

{% block jsfiles %}
{{ super() }}
<script src="{{ url_for('static', filename='js/login.js') }}" type="text/javascript"></script>
{% endblock jsfiles %}

web-twofactor/src/app/templates/auth_mfa.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block description %}Please enter your auth code{% endblock %}

{% block content %}
<div class="container-fluid text-light py-5 px-3">
	<div class="container">
		<h1 class="display-4">Multi Factor</h1>
		{% include "components/alert.html" %}

		<div class="tab-content" id="content">
			<div class="tab-pane fade{% if active_pane == 'mfa' %} show active{% endif %}" id="mfa_pane" role="tabpanel" aria-labelledby="mfa_tab">
				{% for field, errors in mfa_user.errors.items() %}
					<div class="alert alert-info alert-danger alert-dismissible fade show" role="alert">
						{{ mfa_user[field].label }}: {{ ', '.join(errors) }}
						<button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
					</div>
				{% endfor %}
				<form id="mfa_form" action="{{ url_for('main.auth_mfa') }}" name="mfa_form" method="POST">
					<input type="hidden" class="d-none" name="form_name" value="mfa" />
					{{ mfa_user.csrf_token }}
					<div class="mb-3 ">
						{{ mfa_user.code.label(class="form-label") }}
						{{ mfa_user.code(class="form-control") }}
						<small id="codeHelp" class="form-text text-light">Please enter a thing</small>
					</div>
					{{ mfa_user.submit(class='btn btn-primary') }}
				</form>
			</div>
		</div>
	</div>
</div>
{% endblock content %}

{% block jsfiles %}
{{ super() }}
<script src="{{ url_for('static', filename='js/login.js') }}" type="text/javascript"></script>
{% endblock jsfiles %}

web-twofactor/src/app/templates/base.html
<!DOCTYPE html>
<html lang="en">
	<head>

		<title>{% block title %}Unknown{% endblock %} | TwoFactor</title>
		<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
		<meta content="width=device-width, initial-scale=1, maximum-scale=1, shrink-to-fit=no" name="viewport" />
		<meta content="IE=edge" http-equiv="X-UA-Compatible" />
		<meta content="#1a1a1a" name="theme-color" />
		<meta content="{% block description %}This page has no description{% endblock %}" name="description" />

		<meta property="og:locale" content="en_GB" />
		<meta property="og:site_name" content="TwoFactor"/>
		<meta property="og:title" content="{{ self.title() }}" />
		<meta property="og:description" content="{{ self.description() }}" />
		{% if request.base_url %}<meta property="og:url" content="{{ request.base_url }}" />{% endif %}
		{% block pagemeta %}
			<meta property="og:type" content="website" />
		{% endblock %}

		<!-- Some pre-connects to speed up map loading -->
		<link rel="preconnect" href="https://cdnjs.cloudflare.com" />
		<link rel="preconnect" href="https://fonts.gstatic.com" />

		<!-- Page styles -->
		<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/css/bootstrap.min.css"
			  integrity="sha512-SbiR/eusphKoMVVXysTKG/7VseWii+Y3FdHrt0EpKgpToZeemhqHeZeLWLhJutz/2ut2Vw1uQEj2MbRF+TVBUA=="
			  crossorigin="anonymous"
			  referrerpolicy="no-referrer" />
		<link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/styles.css') }}" />

		<!-- Manifest for PWAs -->
		<link rel="manifest" href="{{ url_for('static', filename='manifest.json') }}" />

		<!-- Fonts -->
		<link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;200;300;400;600;700&display=swap" rel="stylesheet" />

		{% block pagehead %}{% endblock pagehead %}

	</head>
	<body>

		<main>
			{% block content %}{% endblock %}
		</main>

		{% block jsfiles %}
		<!-- Run JS code here as to not block page rendering -->
		<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.2.3/js/bootstrap.min.js"
				integrity="sha512-1/RvZTcCDEUjY/CypiMz+iqqtaoQfAITmNSJY17Myp4Ms5mdxPS5UV7iOfdZoxcGhzFbOm6sntTKJppjvuhg4g=="
				crossorigin="anonymous"
				referrerpolicy="no-referrer"></script>
		<script src="{{ url_for('static', filename='js/util.js') }}" type="text/javascript"></script>
		{% endblock %}

	</body>
</html>

web-twofactor/src/app/templates/home.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock title %}

{% block description %}Homepage of application{% endblock %}

{% block content %}
<div class="container-fluid text-light py-5 px-3">
	<div class="container">
		{% include "components/alert.html" %}
		<h1 class="display-4">Logged in as {{current_user.name}}</h1>
		<a class="btn btn-lg btn-danger" href="{{ url_for('main.logout') }}">Logout</a>
	</div>
</div>
{% endblock content %}